# black only support toml configuration...

[tool.black]
line-length = 120
target-version = ['py39']
extend-exclude = """\
    .*/*\\.pyi|\
    .*/*\\_grpc.py|\
    .*/*\\_pb2.py|\
    .*/generated/.*\
"""